# Generated by Django 3.1.4 on 2020-12-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201122_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['id']},
        ),
    ]
